### PR TITLE
Update configure.ac

### PR DESCRIPTION
**Pull request by bizlevel**
better downgrade glib to v2.28. And it is works on CentOS.

### CODE REVIEW

**Comment by megous** [comment]
Megatools uses GBytes, which is available since 2.32:

https://developer.gnome.org/glib/stable/glib-Byte-Arrays.html#g-bytes-new

**Comment by bizlevel** [comment]
Hm.. Lets see how we resolve other dependencies on CentOS.

**Comment by megous** [comment]
It may not be so hot. I grepped the code, and it uses GByteArray, which is a bit older than GBytes. So it may work afterall. You just need to try the alloc.h fix.

**Comment by bizlevel** [comment]
just replace GBytes to GByteArray? It is the same struct?

Old error:

```
  CC     lib/sjson.gen.o
  CC     lib/http.o
  CC     lib/mega.o
In file included from lib/mega.c:24:
lib/alloc.h: In function ‘__cleanup_g_bytes_unref’:
lib/alloc.h:54: error: ‘GBytes’ undeclared (first use in this function)
lib/alloc.h:54: error: (Each undeclared identifier is reported only once
lib/alloc.h:54: error: for each function it appears in.)
lib/alloc.h:54: error: expected expression before ‘)’ token
lib/alloc.h:54: error: expected expression before ‘)’ token
lib/mega.c: In function ‘create_preview’:
lib/mega.c:2812: warning: initialization makes pointer from integer without a cast
lib/mega.c:2848: warning: initialization makes pointer from integer without a cast
make[1]: *** [lib/mega.o] Error 1
make: *** [all] Error 2
```

After change - New another error:

```
[root@srv megatools]#
[root@srv megatools]# make
  CC     lib/mega.o
lib/mega.c: In function ‘create_preview’:
lib/mega.c:2812: warning: initialization makes pointer from integer without a cast
lib/mega.c:2848: warning: initialization makes pointer from integer without a cast
  CC     lib/tools.o
lib/tools.c: In function ‘tool_show_progress’:
lib/tools.c:232: error: ‘G_FORMAT_SIZE_IEC_UNITS’ undeclared (first use in this function)
lib/tools.c:232: error: (Each undeclared identifier is reported only once
lib/tools.c:232: error: for each function it appears in.)
lib/tools.c:232: error: ‘G_FORMAT_SIZE_LONG_FORMAT’ undeclared (first use in this function)
make[1]: *** [lib/tools.o] Error 1
make: *** [all] Error 2
[root@srv megatools]#

```

**Comment by megous** [comment]
Just delete the line. It's probably not worth it to backport. But if you'd like too, it would be acceptable to pull missing functions from newer glib2, and create compat.{c,h} (if there are up to 5 of these functions, and not much more), and only use compat.{c,h} if compiling against glib2 < 2.32.

**Comment by megous** [comment]
Or alternatively disable megatools features that use the newer glib functions when compiling against older glib.

**Comment by bizlevel** [comment]
Maybe nee add some functions from 2.32 glib2.

unfortunately glib2 - is like a core. impossible to fully replace in os.  If megatool will works on CentOS it will work with LD_LIBRARY....
And we can compile from source newest version, for example 2.32.4

```
wget http://ftp.gnome.org/pub/gnome/sources/glib/2.32/glib-2.32.4.tar.xz
configure --prefix=/usr
make
make install
```

After compile i got messages:
```
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for GLIB - version >= 2.32.0...
*** 'pkg-config --modversion glib-2.0' returned 2.32.4, but GLIB (2.28.8)
*** was found! If pkg-config was correct, then it is best
*** to remove the old version of GLib. You may also be able to fix the error
*** by modifying your LD_LIBRARY_PATH enviroment variable, or by editing
*** /etc/ld.so.conf. Make sure you have run ldconfig if that is
*** required on your system.
*** If pkg-config was wrong, set the environment variable PKG_CONFIG_PATH
*** to point to the correct configuration files
no
configure: error: Glib 2.32.0 or later is required to build megatools

[root@srv megatools]#
```

I think maybe need some extra parameters for compliling with external lib (in other dirs. not in /urs/lib, but in /usr/local/lib)

**Comment by megous** [comment]
You need to build to different prefix, in order not to messup your system. Like ~/local. Then you need to set PKG_CONFIG_PATH and some other stuff correctly. But this is generic build info available anywhere on the net. Just search for it.

**Pull request closed without merging**
