### PR TITLE
just a small addition to megacopy

### PR DESCRIPTION
**Pull request by artifexor**
I am picky on local file timestamp so added the timestamp parameter to megacopy. Just simply set the local file and folder timestamp to the file and folder on mega host. Related to issue #253

### CODE REVIEW

**Comment by megous** [comment]
I don't think there needs to be an option for this. It might just as well be a default. It would make the code slightly simpler. Also please don't combine multiple distinct changes into one commit (multiline comment thing) and don't use dash at the beginning of the first line of the commit message.

**Comment by artifexor** [comment]
Roger. I am a beginner in using git, sorry.

**Comment by aaz1887** [comment]
I suggest you to make an additional switch to megacopy.exe, such as --overwrite-if-different-size

Excuse my poor English. Thank you very much

**Comment by megous** [comment]
Tracked in #327

**Pull request closed without merging**
