### PR TITLE
Resume download in cURL

### PR DESCRIPTION
**Pull request by hanxue**
I need some help with this PR. I use `g_file_append_to` to open
the existing file, then set `CURLOPT_RESUME_FROM`, but download
resume still does not work

See Issue #7

### CODE REVIEW

**Comment by megous** [comment]
You also need to initialize the decryption of the stream. Setup the CTR to correct value. CTR is counted in 16 byte chunks (CTR 1 corresponds to file offset 16, and so on). In order to simplify it, you may want to start download offset alligned to 16 bytes.

**Comment by megous** [comment]
CTR is the counter value in AES-CTR.

**Comment by megous** [comment]
Also, you'd either need to initialize CBC-MAC state from already downloaded data, before continuing, or drop the data authentication mechanism completely, when restarting download. (which is not a good idea, probably)

**Comment by christarazi** [comment]
I am trying to implement this. The only difference in my code is that I am using [`CURLOPT_RANGE`](https://curl.haxx.se/libcurl/c/CURLOPT_RANGE.html) because it seems to be for downloading, while [`CURLOPT_RESUME_FROM`](https://curl.haxx.se/libcurl/c/CURLOPT_RESUME_FROM.html) is for uploading. I am having trouble understanding what you mean by initializing the decryption stream, setting up the CBC-MAC. I'd appreciate if you can push me in the right direction, as I'm not too familiar with the codebase and Mega's protocols yet.

**Comment by megous** [comment]
You can look at section 12.10 of https://mega.nz/#doc, which is relevant here.

```
To allow for integrity-checked partial reads, a file is treated as a series of chunks. To simplify server-side processing, partial uploads can only start and end on a chunk boundary. Furthermore, partial downloads can only be integrity-checked if they fulfil the same criterion.
Chunk boundaries are located at the following positions:
0 / 128K / 384K / 768K / 1280K / 1920K / 2688K / 3584K / 4608K / ... (every 1024 KB) / EOF
```

megatools have a cbc_mac calculator that works like a typical hash function interface. (eg. md5_init md5_update - called multiple times for arbitrary blocks of data, md5_finish)

Uploads according to the doc may only start at chunk boundaries, so you would need to store the state of our cbc_mac calculator after successfully finishing uploading up to each boundary, and rollback and restart upload from the boundary.

The same goes probably for downloading.

You may also try to experiment with mega.nz api to see if you can restart from an arbitrary position, which would save you the trouble with saving the cbc-mac calculator state.

Then there is the actual file encryption, where the state consists of a counter, nonce, and perhaps other things I don't remember.

I hope this helps.

**Comment by christarazi** [comment]
Just an update. I was able to get megadl to do partial downloads. I am able to do CBC-MAC and decryption on the chunks of the partial file just fine.

**Comment by megous** [comment]
Closing this. Continued in #252

**Pull request closed without merging**
