### PR TITLE
Option to choose which files to download

### PR DESCRIPTION
**Pull request by dal1a**
Sometimes you don't want to download all files in a shared folder, so I added an option to choose which files to download

### CODE REVIEW

**Comment by megous** [comment]
Looks like a good feature. :+1:  It just needs a better name. --not-all is not very descriptive. Perhaps --choose-files and describe that it only works for folders and that it is interactive. It also needs documentation in the man pages. Finally, I'd put the new code into a separate function that accepts the list and returns a fitlered list.

Also don't use ((struct mega_node*)i->data)->name) because folder can contain subfolders and this will only show the file name and not the entire path and confuse users in case of sub-folders.

**Comment by megous** [comment]
Code is better. It looks a bit too complicated so I didn't add it to 1.10.0, which I wanted to release today. I'll look at it for the future release. Thanks for the changes.

**Comment by megous** [comment]
Merged. Thanks.

**Comment by dal1a** [comment]
Hi, I see you've changed the tree view to showing absolute paths and I was wondering if you'd consider changing it back. I understand that with full path there's very little space for user confusion, but on the other hand with tree view it'll take a lot less horizontal space (which means fewer line cuts in terminal) and it'll be easier to see which number corresponds to which file (with full path it could get difficult to find the right number without the use of a mouse highlight because first n characters are the same). Anyway, here's how I approached it: https://github.com/dal1a/megatools/commit/1055bb1f24f0ea689d8c2c580ec84a0cc1882fa8 I didn't want to create a new pull request because of such a small change. Please consider it. Thanks.

**Comment by megous** [comment]
That was not intentional. It was just a part of refactoring to use mega_session_ls/bugfixing.

I don't mind putting it back.

**Comment by dal1a** [comment]
That would be great. I just realized that the solution I have in my commit very much relies on the nodes being sorted: ["folder", "folder/item", "folder/item2", "different_folder", "different_folder/item", ...]. Which wouldn't work if there were folders like "folder" "folder-version-2" because '-' < '/'. So I also had to slightly change the compare function here: https://github.com/dal1a/megatools/commit/3ce4c5d0bad7c73250410936644bdfe5c475e13e which shouldn't be in a way of anything since it's only used in the pick_nodes function.

I'm also not sure if there's a prettier way to change terminal color than straight up putting terminal escape codes into g_print, if you know of something, please change it :)

**Comment by megous** [comment]
It is sorted. One way to deal with fodlders is put the / at the end, yes. I see you're doing that. :)

Just don't use colors. :) Other nice solution is to do pre-processing of the format string by using a custom wrapper around vprintf. But that's overkill for those two places where megatools use color, atm.

With a wrapper you could make it so that:

  color_printf("[red]%s[reset]", somevar);

would change the color, or even ignore color markers on dumb terminals/file redirection.

You would even be able to:

  color_printf("[@important]%s[reset]", somevar);

create named colors, where the user can define his favorite colors in some file.

**Pull request closed without merging**
