### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by megous** [comment]
The section is meant for compilation from the tarball. You shouldn't need autotools, nor asciidoc for that. Though, it may be useful to add a section to HACKING about dependencies for whoever wants to develop megatools/build from git tree.

**Comment by PeterDaveHello** [comment]
Yes, I downloaded the tarball, but I have no `configure` file there, so I run `autogen.sh` first, and I found that I need these tools, don't know if I missing something ...

**Comment by megous** [comment]
Official tarballs are available here: http://megatools.megous.com/

Github releases page contains just a packed state of the git repo. I guess that's what you've downloaded.

**Comment by PeterDaveHello** [comment]
Oh, thanks, I'll try it, thank you.

**Pull request closed without merging**
